server:
  port: 8082

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/jongno?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  liquibase:
    change-log: classpath:/schema/changelog-master.xml
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true